backend:
  name: git-gateway
  branch: main
  repo: giri-tech-assets/gatsby-starter-decap-cms
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "faq"
    label: "FAQ"
    folder: "content/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "select", options: ["buyer", "seller"]}
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number", default: 1}
    sortable_fields: ['order', 'title']
    view_filters:
      - label: "Buyer FAQs"
        field: type
        pattern: "buyer"
      - label: "Seller FAQs"
        field: type
        pattern: "seller"
    view_groups:
      - label: Type
        field: type
  - name: 'policies'
    label: 'Policies'
    folder: 'content/policies'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Last Updated', name: 'lastUpdated', widget: 'date', format: 'MMMM YYYY' }
      - { label: 'Introduction', name: 'introduction', widget: 'text' }
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string' }
          - { label: 'Section Content', name: 'content', widget: 'markdown' }
      - { label: 'Contact Information', name: 'contact', widget: 'text' }

  - name: 'terms'
    label: 'Terms'
    folder: 'content/terms'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Last Updated', name: 'lastUpdated', widget: 'date', format: 'MMMM YYYY' }
      - { label: 'Introduction', name: 'introduction', widget: 'text' }
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string' }
          - { label: 'Section Content', name: 'content', widget: 'markdown' }
      - { label: 'Contact Information', name: 'contact', widget: 'text' }
